#include "pages.h"
#include "utils.h"

String Pages::createRoutinePage(){
  String buf = "";
  buf += "<!DOCTYPE html>";
  buf += "<html lang='pt-BR'>";
  buf += "<head>";
  buf += "    <meta charset='UTF-8'>";
  buf += "    <meta http-equiv='X-UA-Compatible' content='IE=edge'>";
  buf += "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
  buf += "    <title>IrrigAuto</title>";
  buf += "</head>";
  buf += "<style>";

  buf += "* {";
  buf += "  box-sizing: border-box;";
  buf += "  margin: 0;";
  buf += "  padding: 0;";
  buf += "  font-family: 'Inter', sans-serif;";
  buf += "  text-align: center;";
  buf += "  color: #403937;";
  buf += "}";
  buf += ":root {";
  buf += "  font-size: 62.5%;";
  buf += "}";
  buf += "body {";
  buf += "  width: 100vw;";
  buf += "  height: 100vh;";
  buf += "  background: linear-gradient(107.56deg, #5D5F28 0%, rgba(32, 90, 38, 0.557143) 32.29%, rgba(26, 87, 32, 0.264286) 53.65%,";
  buf += "      rgba(30, 30, 30, 0) 100%);";
  buf += "  background-color: #1E1E1E;";
  buf += "}";
  buf += ".wrapper {";
  buf += "  display: flex;";
  buf += "  align-items: center;";
  buf += "  justify-content: center;";
  buf += "}";
  buf += ".app {";
  buf += "  min-height: 100vh;";
  buf += "  max-width: 97.4rem;";
  buf += "  padding: 2rem 1rem;";
  buf += "  background-color: #D9D9D9;";
  buf += "  display: flex;";
  buf += "  flex-direction: column;";
  buf += "  align-items: center;";
  buf += "  gap: 3rem;";
  buf += "}";
  buf += ".timers-container {";
  buf += "  display: flex;";
  buf += "  flex-direction: row;";
  buf += "  gap: 2rem;";
  buf += "}";
  buf += ".timer {";
  buf += "  display: flex;";
  buf += "  gap: 2rem;";
  buf += "}";
  buf += ".timer-selector {";
  buf += "  display: flex;";
  buf += "  flex-direction: row;";
  buf += "  align-items: center;";
  buf += "  gap: 0.3rem;";
  buf += "}";
  buf += ".timer-container {";
  buf += "  display: flex;";
  buf += "  flex-direction: column;";
  buf += "}";
  buf += ".timer-container div {";
  buf += "  display: flex;";
  buf += "  justify-content: center;";
  buf += "  align-items: center;";
  buf += "  width: 6rem;";
  buf += "  height: 6rem;";
  buf += "  background: #CDCDCD;";
  buf += "  box-shadow: inset 4px 4px 4px rgba(0, 0, 0, 0.25);";
  buf += "  font-size: 4rem;";
  buf += "}";
  buf += ".timer-container button {";
  buf += "  margin-top: 0.2rem;";
  buf += "  width: 100%;";
  buf += "  height: 6rem;";
  buf += "  background: #8AC880;";
  buf += "  border: none;";
  buf += "  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);";
  buf += "  font-weight: 900;";
  buf += "  font-size: 36px;";
  buf += "  color: #ffffff;";
  buf += "  cursor: pointer;";
  buf += "  transition: 200ms;";
  buf += "}";
  buf += ".timer-container button:first-child {";
  buf += "  border-radius: 10px 10px 0 0;";
  buf += "}";
  buf += ".timer-container button:last-child {";
  buf += "  border-radius: 0 0 10px 10px;";
  buf += "}";
  buf += ".timer {";
  buf += "  display: flex;";
  buf += "  flex-direction: column;";
  buf += "}";
  buf += ".timer p {";
  buf += "  font-size: 4rem;";
  buf += "}";
  buf += ".footer {";
  buf += "  display: flex;";
  buf += "  width: 100%;";
  buf += "  max-width: 97.4rem;";
  buf += "}";
  buf += ".footer button {";
  buf += "  border: 0;";
  buf += "  border-radius: 10px 0 0 10px;";
  buf += "  width: 100%;";
  buf += "  padding: 1rem;";
  buf += "  background-color: #3B64B2;";
  buf += "  color: #FFFFFF;";
  buf += "  font-weight: 700;";
  buf += "  font-size: 2rem;";
  buf += "  text-decoration: none;";
  buf += "  transition: 200ms;";
  buf += "}";
  buf += "#cancel-button {";
  buf += "  border-radius: 0 10px 10px 0;";
  buf += "  background-color: #B2433B;";
  buf += "}";
  buf += "@media (max-width: 952px) {";
  buf += "  .app {";
  buf += "    width: 100vw;";
  buf += "  }";
  buf += "}";

  buf += ".relaysContainer {";
  buf += "  display: grid;";
  buf += "  grid-template-columns: repeat(4, 1fr);";
  buf += "}";

  buf += ".relaysContainer button:first-child {";
  buf += "  border-top-left-radius: 10px;";
  buf += "}";

  buf += ".relaysContainer button:nth-child(4) {";
  buf += "  border-top-right-radius: 10px;";
  buf += "}";

  buf += ".relaysContainer button:last-child {";
  buf += "  border-bottom-right-radius: 10px;";
  buf += "}";

  buf += ".relaysContainer button:nth-child(5n + 1):nth-last-child(-n + 5) {";
  buf += "  border-bottom-left-radius: 10px;";
  buf += "}";

  buf += ".selectRelayButton {";
  buf += "  border: 2px solid #ffffff;";
  buf += "  padding: 0.5rem;";
  buf += "  border-radius: 0;";
  buf += "  background-color: #A64D4D;";
  buf += "  color: #ffffff;";
  buf += "}";

  buf += ".selectRelayButton h1 {";
  buf += "  font-size: 3rem;";
  buf += "  color: #ffffff;";
  buf += "}";

  buf += ".selectRelayButton p {";
  buf += "	font-size: 1.5rem;";
  buf += "	color: #ffffff;";
  buf += "	font-weight: 600;";
  buf += "}";

  buf += ".selectRelayButton label {";
  buf += "  color: #ffffff;";
  buf += "  font-size: 1.3rem;";
  buf += "}";

  buf += "header p {";
  buf += "  font-size: 1.3rem;";
  buf += "}";

  buf += "header {";
  buf += "  display: flex;";
  buf += "  flex-direction: column;";
  buf += "  align-items: center;";
  buf += "  gap: 1rem;";
  buf += "}";

  buf += ".selectedPort {";
  buf += "  color: #ffffff;";
  buf += "  background-color: #8AC87F;";
  buf += "}";


  buf += "</style>";
  buf += "<body>";
  buf += "    <div class='wrapper'>";
  buf += "        <div class='app'>";
  buf += "            <h1>configurar rotina</h1>";
  buf += "            <div class='header'>";

  buf += "      <p>";
  buf += "        Selecionar porta";
  buf += "      </p>";
  buf += "              <div class='relaysContainer'>";
  for(int i = 0; i<NUMBER_OF_RELAYS; i++){
    buf += "        <button class='selectRelayButton ";
    buf+="' ";
    buf+="id='selectRelayButton-";
    buf+=numberToTwoChars(relays[i].id);
    buf+= "' ";
    buf+="onclick='selectRelay(\""+numberToTwoChars(relays[i].id)+"\")'\n";
    buf += "          <p>porta</p>";
    buf += "          <h1>"+String(relays[i].id)+"</h1>";
    buf += "        </button>";
  }

  buf += "      </div>";
  buf += "    </div>  ";
  buf += "            <div class='timers-container'>";
  buf += "                <div class='timer'>";
  buf += "                    <h1>liga:</h1>";
  buf += "                    <div class='timer-selector'>";
  buf += "                        <div class='timer-container'>";
  buf += "                            <button onclick='somarHoraLiga(5)'>+5</button>";
  buf += "                            <button onclick='somarHoraLiga(1)'>+1</button>";
  buf += "                            <div id='horaLiga'>0</div>";
  buf += "                            <button onclick='somarHoraLiga(-1)' style='background-color: #D45C5C;'>-1</button>";
  buf += "                            <button onclick='somarHoraLiga(-5)' style='background-color: #D45C5C;'>-5</button>";
  buf += "                        </div>";
  buf += "                        <p>:</p>";
  buf += "                        <div class='timer-container'>";
  buf += "                            <button onclick='somarMinutosLiga(5)'>+5</button>";
  buf += "                            <button onclick='somarMinutosLiga(1)'>+1</button>";
  buf += "                            <div id='minutoLiga'>0</div>";
  buf += "                            <button onclick='somarMinutosLiga(-1)' style='background-color: #D45C5C;'>-1</button>";
  buf += "                            <button onclick='somarMinutosLiga(-5)' style='background-color: #D45C5C;'>-5</button>";
  buf += "                        </div>";
  buf += "                    </div>";
  buf += "                </div>";
  buf += "                <div class='timer'>";
  buf += "                    <h1>desliga:</h1>";
  buf += "                    <div class='timer-selector'>";
  buf += "                        <div class='timer-container'>";
  buf += "                            <button onclick='somarHoraDesliga(5)'>+5</button>";
  buf += "                            <button onclick='somarHoraDesliga(1)'>+1</button>";
  buf += "                            <div id='horaDesliga'>0</div>";
  buf += "                            <button onclick='somarHoraDesliga(-1)' style='background-color: #D45C5C;'>-1</button>";
  buf += "                            <button onclick='somarHoraDesliga(-5)' style='background-color: #D45C5C;'>-5</button>";
  buf += "                        </div>";
  buf += "                        <p>:</p>";
  buf += "                        <div class='timer-container'>";
  buf += "                            <button onclick='somarMinutosDesliga(5)'>+5</button>";
  buf += "                            <button onclick='somarMinutosDesliga(1)'>+1</button>";
  buf += "                            <div id='minutoDesliga'>0</div>";
  buf += "                            <button onclick='somarMinutosDesliga(-1)' style='background-color: #D45C5C;'>-1</button>";
  buf += "                            <button onclick='somarMinutosDesliga(-5)' style='background-color: #D45C5C;'>-5</button>";
  buf += "                        </div>";
  buf += "                    </div>";
  buf += "                </div>";
  buf += "            </div>";
  buf += "            <div class='footer'>";
  buf += "                <button onclick='confirmar()'>confirmar</button>";
  buf += "                <button onclick='cancelar()' id='cancel-button' href='/'>cancelar</a>";
  buf += "            </div>";
  buf += "        </div>";
  buf += "    </div>";
  buf += "</body>";
  buf += "<script>";
  buf += "  let relayId;\n";
  buf += "  function selectRelay(id){\n";
  buf += "    const manualButton = window.document.getElementById(`selectRelayButton-${id}`)\n";
  buf += "    const lastManualButton = window.document.getElementById(`selectRelayButton-${relayId}`)\n";
  buf += "    manualButton.classList.add('selectedPort')\n";
  buf += "    if(lastManualButton){\n";
  buf += "      lastManualButton.classList.remove('selectedPort')\n";
  buf += "    }\n";
  buf += "    relayId = id\n";
  buf += "  }\n";
  buf += "  let horasLiga = 0\n";
  buf += "  let minutosLiga = 0\n";
  buf += "  function atualizarDisplayLiga() {\n";
  buf += "      const displayMinutos = window.document.getElementById('minutoLiga')\n";
  buf += "      const displayHoras = window.document.getElementById('horaLiga')\n";
  buf += "      displayMinutos.innerHTML = minutosLiga\n";
  buf += "      displayHoras.innerHTML = horasLiga\n";
  buf += "  }\n";
  buf += "  function somarHoraLiga(valor) {\n";
  buf += "    if (horasLiga + valor > 23) {\n";
  buf += "        horasLiga = 0\n";
  buf += "    } else if (horasLiga + valor < 0) {\n";
  buf += "        horasLiga = 23\n";
  buf += "    } else {\n";
  buf += "        horasLiga = horasLiga + valor\n";
  buf += "    }\n";
  buf += "    atualizarDisplayLiga()\n";
  buf += "  }\n";
  buf += "  function somarMinutosLiga(valor) {\n";
  buf += "      if (minutosLiga + valor > 59) {\n";
  buf += "          minutosLiga = 0\n";
  buf += "      } else if (minutosLiga + valor < 0) {\n";
  buf += "          minutosLiga = 59\n";
  buf += "      } else {\n";
  buf += "          minutosLiga = minutosLiga + valor\n";
  buf += "      }\n";
  buf += "      atualizarDisplayLiga()\n";
  buf += "  }\n";
  buf += "  let horasDesliga = 0\n";
  buf += "  let minutosDesliga = 0\n";
  buf += "  function atualizarDisplayDesliga() {\n";
  buf += "      const displayMinutos = window.document.getElementById('minutoDesliga')\n";
  buf += "      const displayHoras = window.document.getElementById('horaDesliga')\n";
  buf += "      displayMinutos.innerHTML = minutosDesliga\n";
  buf += "      displayHoras.innerHTML = horasDesliga\n";
  buf += "  }\n";
  buf += "  function somarHoraDesliga(valor) {\n";
  buf += "      if (horasDesliga + valor > 23) {\n";
  buf += "          horasDesliga = 0\n";
  buf += "      } else if (horasDesliga + valor < 0) {\n";
  buf += "          horasDesliga = 23\n";
  buf += "      } else {\n";
  buf += "          horasDesliga = horasDesliga + valor\n";
  buf += "      }\n";
  buf += "      atualizarDisplayDesliga()\n";
  buf += "  }\n";
  buf += "  function somarMinutosDesliga(valor) {\n";
  buf += "      if (minutosDesliga + valor > 59) {\n";
  buf += "          minutosDesliga = 0\n";
  buf += "      } else if (minutosDesliga + valor < 0) {\n";
  buf += "          minutosDesliga = 59\n";
  buf += "      } else {\n";
  buf += "          minutosDesliga = minutosDesliga + valor\n";
  buf += "      }\n";
  buf += "      atualizarDisplayDesliga()\n";
  buf += "  }\n";
  buf += "  function cancelar() {\n";
  buf += "      window.location.replace('/')\n";
  buf += "  }\n";
  buf += "  function ftd(number) {\n";
  buf += "    return number.toString().padStart(2, '0');\n";
  buf += "  }\n";
  buf += "  async function confirmar() {\n";
  buf += "    if(!relayId){\n";
  buf += "      alert('Porta não selecionada')\n";
  buf += "      return\n";
  buf += "    }\n";
  buf += "    const response = await fetch(`/adicionar-rotina?rotina=${ftd(horasLiga)}${ftd(minutosLiga)}${ftd(horasDesliga)}${ftd(minutosDesliga)}${ftd(relayId)}`);\n";
  buf += "    if(response.status != 200){\n";
  buf += "      const data = await response.json();\n";
  buf += "      alert(data.message)\n";
  buf += "      return\n";
  buf += "    }\n";
  buf += "    window.location.replace('/')\n";
  buf += "  }\n";
  buf += "</script>";
  buf += "</html>";

  return buf;
}