#include "pages.h"

String Pages::configureNetwork(){
  String buf = "";
  buf += "<html lang='pt-BR'>";
  buf += "<head>";
  buf += "  <meta charset='UTF-8'>";
  buf += "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
  buf += "  <title>IrrigAuto</title>";
  buf += "  <style>";
  buf += "    * {";
  buf += "      box-sizing: border-box;";
  buf += "      margin: 0;";
  buf += "      padding: 0;";
  buf += "      font-family: 'Inter', sans-serif;";
  buf += "      text-align: center;";
  buf += "      color: #403937;";
  buf += "      font-size: 1.6rem;";
  buf += "    }";
  buf += "    :root {";
  buf += "      font-size: 62.5%;";
  buf += "    }";
  buf += "    body {";
  buf += "      width: 100vw;";
  buf += "      height: 100vh;";
  buf += "      background: linear-gradient(107.56deg, #5D5F28 0%, rgba(32, 90, 38, 0.557143) 32.29%, rgba(26, 87, 32, 0.264286) 53.65%, rgba(30, 30, 30, 0) 100%);";
  buf += "      background-color: #1E1E1E;";
  buf += "    }";
  buf += "    .wrapper {";
  buf += "      display: flex;";
  buf += "      align-items: center;";
  buf += "      justify-content: center;";
  buf += "    }";
  buf += "    .app {";
  buf += "      height: 100vh;";
  buf += "      max-width: 97.4rem;";
  buf += "      width: 100%;";
  buf += "      padding: 2rem 1rem;";
  buf += "      background-color: #D9D9D9;";
  buf += "      display: flex;";
  buf += "      flex-direction: column;";
  buf += "      align-items: center;";
  buf += "      gap: 3rem;";
  buf += "    }";
  buf += "    @media (max-width: 952px) {";
  buf += "      .app {";
  buf += "        width: 100vw;";
  buf += "      }";
  buf += "    }";
  buf += "    .modeSelectorContainer {";
  buf += "      display: grid;";
  buf += "      grid-template-rows: 1fr 1fr;";
  buf += "      gap: 2rem;";
  buf += "    }";
  buf += "    .modeSelectorContainer label {";
  buf += "      display: grid;";
  buf += "      grid-template-columns: 1fr 12fr;";
  buf += "      align-items: center;";
  buf += "      gap: 0.4rem;";
  buf += "    }";
  buf += "    .modeSelectorContainer label input {";
  buf += "      height: 100%;";
  buf += "      width: 100%;";
  buf += "      background-color: green;";
  buf += "    }";
  buf += "    h1 {";
  buf += "      font-size: 2rem;";
  buf += "    }";
  buf += "    form {";
  buf += "      display: flex;";
  buf += "      flex-direction: column;";
  buf += "      gap: 2rem;";
  buf += "    }";
  buf += "    .inputsContainer {";
  buf += "      display: flex;";
  buf += "      flex-direction: column;";
  buf += "      gap: 1rem;";
  buf += "    }";
  buf += "    .inputsContainer div {";
  buf += "      display: flex;";
  buf += "      flex-direction: column;";
  buf += "      align-items: flex-start;";
  buf += "    }";
  buf += "    .inputsContainer div input {";
  buf += "      width: 100%;";
  buf += "      height: 4rem;";
  buf += "      border-radius: 10px;";
  buf += "      border: none;";
  buf += "      text-align: left;";
  buf += "      padding: 1rem;";
  buf += "      box-shadow: inset 4px 4px 4px rgba(0, 0, 0, 0.25);";
  buf += "    }";
  buf += "    .inputsContainer div label {";
  buf += "      margin-left: 1rem;";
  buf += "    }";
  buf += "    button {";
  buf += "      border: 0;";
  buf += "      border-radius: 10px;";
  buf += "      width: 100%;";
  buf += "      padding: 1rem;";
  buf += "      background-color: #8AC880;";
  buf += "      color: #FFFFFF;";
  buf += "      font-weight: 700;";
  buf += "      font-size: 2rem;";
  buf += "      text-decoration: none;";
  buf += "      transition: 200ms;";
  buf += "    }";
  buf += "  </style>";
  buf += "</head>";
  buf += "<body>";
  buf += "  <div class='wrapper'>";
  buf += "    <div class='app'>";
  buf += "      <header>";
  buf += "        <h1>configurar conexão</h1>";
  buf += "      </header>";
  buf += "      <form onsubmit='handleFormSubmition(event)'>";
  buf += "        <div class='modeSelectorContainer'> <label> <input type='radio' name='mode' value='AP' checked="">";
  buf += "            <p>Desejo usar o aparelho como ponto de acesso wifi e me conectar a ele para gerenciá-lo.</p>";
  buf += "          </label> <label> <input type='radio' name='mode' value='STA'>";
  buf += "            <p>Desejo que meu aparelho se conecte a uma rede existente.</p>";
  buf += "          </label> </div>";
  buf += "        <div class='inputsContainer'>";
  buf += "          <div> <label><strong>Nome da rede:</strong></label> <input type='text' name='ssid' id='ssid'> </div>";
  buf += "          <div> <label><strong>Senha da rede:</strong></label> <input type='text' name='password' id='password'> </div>";
  buf += "        </div> <button type='submit'>confirmar</button>";
  buf += "      </form>";
  buf += "    </div>";
  buf += "  </div>";
  buf += "  <script>  ";
  buf += "    function handleFormSubmition(event) {\n";
  buf += "      event.preventDefault()\n";
  buf += "      const mode = document.querySelector(`input[name='mode']:checked`).value;\n";
  buf += "      const ssid = document.getElementById('ssid').value;\n";
  buf += "      const password = document.getElementById('password').value;\n";
  buf += "      location.replace(`/configurar-rede?ssid=${ssid}&password=${password}&mode=${mode}`);\n";
  buf += "    }\n";
  buf += "  </script>";
  buf += "</body>";
  buf += "</html>";
  return buf;
}